# Generated by Django 5.0.1 on 2026-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='国際番号対応のため20文字まで', max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('adopter', '飼い主希望者'), ('shelter', '保護団体スタッフ'), ('admin', '管理者')], default='adopter', max_length=10, verbose_name='ユーザー種別'),
        ),
        migrations.DeleteModel(
            name='ShelterProfile',
        ),
    ]
