# Generated by Django 4.2.28 on 2026-02-08 04:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='年齢')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('no_answer', '回答しない')], help_text='団体提出用（スコアに使わない）', max_length=20, null=True, verbose_name='性別')),
                ('residence_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='居住エリア（都道府県 / 市区町村）')),
                ('housing_type', models.CharField(blank=True, choices=[('owned', '持ち家'), ('rented', '賃貸')], max_length=20, null=True, verbose_name='住宅形態')),
                ('pet_allowed', models.CharField(blank=True, choices=[('allowed', '可（契約書あり）'), ('planned', '確認予定'), ('not_allowed', '不可')], max_length=20, null=True, verbose_name='ペット可否')),
                ('indoors_agreement', models.BooleanField(default=False, verbose_name='完全室内飼いへの同意（必須）')),
                ('absence_time', models.CharField(blank=True, choices=[('less_than_4', '4時間未満'), ('4_to_8', '4〜8時間'), ('8_to_12', '8〜12時間'), ('more_than_12', '12時間以上')], max_length=20, null=True, verbose_name='平均留守時間')),
                ('home_frequency', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=20, null=True, verbose_name='在宅頻度')),
                ('cat_experience', models.CharField(blank=True, choices=[('none', 'なし'), ('one', 'あり'), ('multiple', '複数経験')], max_length=20, null=True, verbose_name='猫の飼育経験')),
                ('cat_distance', models.CharField(blank=True, choices=[('clingy', 'べったり'), ('moderate', '適度'), ('watchful', '見守り型')], max_length=20, null=True, verbose_name='猫との距離感')),
                ('home_atmosphere', models.CharField(blank=True, choices=[('quiet', '静か'), ('normal', '普通'), ('lively', 'にぎやか')], max_length=20, null=True, verbose_name='家の雰囲気')),
                ('visitor_frequency', models.CharField(blank=True, choices=[('high', '多い'), ('medium', '普通'), ('low', '少ない')], max_length=20, null=True, verbose_name='来客頻度')),
                ('moving_plan', models.CharField(blank=True, choices=[('none', 'なし'), ('within_1_2_years', '1–2年以内'), ('undecided', '未定')], max_length=20, null=True, verbose_name='引っ越し予定')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
