# Generated by Django 5.0.1 on 2026-02-05 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='団体名')),
                ('representative', models.CharField(max_length=100, verbose_name='代表者名')),
                ('website_url', models.URLField(blank=True, verbose_name='公式サイトURL')),
                ('address', models.TextField(verbose_name='住所')),
                ('contact_info', models.CharField(help_text='電話番号またはメールアドレス', max_length=200, verbose_name='連絡先')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='登録番号')),
                ('description', models.TextField(blank=True, verbose_name='団体説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '保護団体',
                'verbose_name_plural': '保護団体',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShelterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('staff', 'スタッフ'), ('volunteer', 'ボランティア')], default='staff', max_length=20, verbose_name='役割')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='参加日時')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_users', to='shelters.shelter', verbose_name='保護団体')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '保護団体メンバー',
                'verbose_name_plural': '保護団体メンバー',
                'indexes': [models.Index(fields=['shelter'], name='shelters_sh_shelter_8895b9_idx'), models.Index(fields=['user'], name='shelters_sh_user_id_d7fa18_idx')],
                'unique_together': {('shelter', 'user')},
            },
        ),
    ]
