# Generated by Django 5.0.1 on 2026-02-06 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shelteruser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='shelteruser',
            constraint=models.UniqueConstraint(fields=('shelter', 'user'), name='unique_shelter_user'),
        ),
    ]
