# Generated by Django 4.2.28 on 2026-02-07 12:06

from django.db import migrations, models


def migrate_contact_info_to_phone(apps, schema_editor):
    """既存の contact_info データを phone フィールドに移行"""
    Shelter = apps.get_model('shelters', 'Shelter')
    for shelter in Shelter.objects.all():
        if hasattr(shelter, 'contact_info') and shelter.contact_info:
            shelter.phone = shelter.contact_info
            shelter.save()


def reverse_migrate(apps, schema_editor):
    """逆マイグレーション: phone を contact_info に戻す"""
    Shelter = apps.get_model('shelters', 'Shelter')
    for shelter in Shelter.objects.all():
        if shelter.phone:
            shelter.contact_info = shelter.phone
            shelter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_alter_shelteruser_unique_together_and_more'),
    ]

    operations = [
        # Step 1: 新しいフィールドを追加
        migrations.AddField(
            model_name='shelter',
            name='email',
            field=models.EmailField(blank=True, help_text='例: info@example.com', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone',
            field=models.CharField(blank=True, help_text='例: 03-1234-5678', max_length=20, verbose_name='電話番号'),
        ),
        # Step 2: 既存データを移行
        migrations.RunPython(migrate_contact_info_to_phone, reverse_migrate),
        # Step 3: 古いフィールドを削除
        migrations.RemoveField(
            model_name='shelter',
            name='contact_info',
        ),
    ]
