# Generated by Django 4.2.28 on 2026-02-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0003_split_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='business_hours',
            field=models.TextField(blank=True, help_text='例: 平日11:00-20:00, 土日祝10:00-19:00, 定休日: 水曜', verbose_name='営業日・営業時間・定休日'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(default='〇〇区', max_length=100, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='contact_verified',
            field=models.BooleanField(default=False, verbose_name='連絡先確認済み'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='prefecture',
            field=models.CharField(default='東京都', max_length=50, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='shelter_type',
            field=models.CharField(choices=[('cafe', '保護猫カフェ')], default='cafe', max_length=20, verbose_name='種別'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='sns_url',
            field=models.URLField(blank=True, help_text='InstagramやTwitterなど', verbose_name='SNS URL'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='transfer_available_hours',
            field=models.TextField(blank=True, help_text='例: 平日14:00-16:00', verbose_name='譲渡対応可能な時間帯'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='verification_status',
            field=models.CharField(choices=[('pending', '審査中'), ('verified', '認証済み'), ('rejected', '否認'), ('suspended', '停止中')], default='pending', max_length=20, verbose_name='審査ステータス'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.TextField(verbose_name='店舗住所'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(default='', help_text='必須・一部非公開', max_length=254, verbose_name='代表メールアドレス'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='カフェ名（団体名）'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(default='', help_text='必須・非公開', max_length=20, verbose_name='代表電話番号'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='動物取扱業登録番号'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='representative',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
    ]
