# Generated by Django 4.2.28 on 2026-02-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0004_shelter_business_hours_shelter_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='郵便番号'),
        ),
    ]
