# Generated by Django 4.2.28 on 2026-02-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0005_shelter_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='review_message',
            field=models.TextField(blank=True, help_text='承認・差し戻し・お見送りの際の理由や連絡事項', verbose_name='審査メッセージ'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='verification_status',
            field=models.CharField(choices=[('pending', '審査中'), ('approved', '承認済み'), ('rejected', '否認'), ('need_fix', '修正依頼中'), ('suspended', '利用停止中')], default='pending', max_length=20, verbose_name='審査ステータス'),
        ),
    ]
