# Generated by Django 5.0.1 on 2026-02-05 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('gender', models.CharField(choices=[('male', 'オス'), ('female', 'メス'), ('unknown', '不明')], max_length=10, verbose_name='性別')),
                ('age_years', models.IntegerField(default=0, verbose_name='年齢（年）')),
                ('age_months', models.IntegerField(default=0, verbose_name='年齢（月）')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='品種')),
                ('size', models.CharField(choices=[('small', '小型'), ('medium', '中型'), ('large', '大型')], default='medium', max_length=10, verbose_name='体格')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='毛色')),
                ('personality', models.TextField(verbose_name='性格')),
                ('health_status', models.TextField(verbose_name='健康状態')),
                ('vaccination', models.BooleanField(default=False, verbose_name='ワクチン接種済み')),
                ('neutered', models.BooleanField(default=False, verbose_name='去勢・避妊済み')),
                ('description', models.TextField(verbose_name='説明')),
                ('status', models.CharField(choices=[('open', '募集中'), ('paused', '一時停止'), ('in_review', '審査中'), ('trial', 'トライアル中'), ('adopted', '譲渡済み')], default='open', max_length=20, verbose_name='募集状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='保護団体')),
            ],
            options={
                'verbose_name': '保護猫',
                'verbose_name_plural': '保護猫',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cats/', verbose_name='画像')),
                ('image_url', models.URLField(blank=True, help_text='外部ストレージ（S3等）のURL', verbose_name='画像URL')),
                ('is_primary', models.BooleanField(default=False, verbose_name='メイン画像')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cats.cat', verbose_name='保護猫')),
            ],
            options={
                'verbose_name': '保護猫画像',
                'verbose_name_plural': '保護猫画像',
                'ordering': ['-is_primary', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='cats/videos/', verbose_name='動画ファイル')),
                ('video_url', models.URLField(blank=True, help_text='外部ストレージ（S3等）のURL', verbose_name='動画URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cats.cat', verbose_name='保護猫')),
            ],
            options={
                'verbose_name': '保護猫動画',
                'verbose_name_plural': '保護猫動画',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
