# Generated by Django 5.0.1 on 2026-02-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='shelters.shelter', verbose_name='保護団体'),
        ),
    ]
