# Generated by Django 5.0.1 on 2026-02-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='キャプション'),
        ),
        migrations.AddField(
            model_name='catvideo',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='キャプション'),
        ),
    ]
