# Generated by Django 5.0.1 on 2026-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_catimage_caption_catvideo_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='catvideo',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='catvideo',
            name='video',
            field=models.FileField(default='', upload_to='cats/videos/', verbose_name='動画ファイル'),
            preserve_default=False,
        ),
    ]
