# Generated by Django 5.0.1 on 2026-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_remove_catimage_image_url_remove_catvideo_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='catvideo',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
