# Generated by Django 5.0.1 on 2026-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_alter_catimage_sort_order_alter_catvideo_sort_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='catimage',
            index=models.Index(fields=['cat', 'sort_order'], name='cats_catima_cat_id_fc579d_idx'),
        ),
        migrations.AddIndex(
            model_name='catvideo',
            index=models.Index(fields=['cat', 'sort_order'], name='cats_catvid_cat_id_c25be3_idx'),
        ),
    ]
