# Generated by Django 4.2.28 on 2026-02-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_catimage_cats_catima_cat_id_fc579d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='health_status',
        ),
        migrations.AddField(
            model_name='cat',
            name='activity_level',
            field=models.CharField(choices=[('active', '活発'), ('normal', '普通'), ('calm', 'おっとり'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='活発さ'),
        ),
        migrations.AddField(
            model_name='cat',
            name='age_category',
            field=models.CharField(choices=[('kitten', '子猫'), ('adult', '成猫'), ('senior', 'シニア猫'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='年齢区分'),
        ),
        migrations.AddField(
            model_name='cat',
            name='estimated_age',
            field=models.CharField(default='', help_text='例: 2歳くらい, 2023年春生まれ', max_length=100, verbose_name='推定年齢'),
        ),
        migrations.AddField(
            model_name='cat',
            name='fee_details',
            field=models.TextField(blank=True, verbose_name='費用に含まれる内容'),
        ),
        migrations.AddField(
            model_name='cat',
            name='fiv_felv_status',
            field=models.CharField(choices=[('negative', '陰性'), ('positive_fiv', 'FIV陽性'), ('positive_felv', 'FeLV陽性'), ('positive_double', 'ダブルキャリア'), ('untested', '未検査'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='ウイルス検査（FIV/FeLV）'),
        ),
        migrations.AddField(
            model_name='cat',
            name='health_notes',
            field=models.TextField(blank=True, verbose_name='健康状態詳細'),
        ),
        migrations.AddField(
            model_name='cat',
            name='health_status_category',
            field=models.CharField(choices=[('healthy', '問題なし'), ('needs_care', 'ケアあり'), ('treatment', '継続治療'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='健康状態区分'),
        ),
        migrations.AddField(
            model_name='cat',
            name='human_distance',
            field=models.CharField(choices=[('cuddly', '抱っこ好き'), ('ok', '抱っこ可'), ('shy', '抱っこ苦手'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='人への距離感（抱っこ）'),
        ),
        migrations.AddField(
            model_name='cat',
            name='interview_format',
            field=models.CharField(choices=[('online', 'オンライン'), ('offline', '対面'), ('both', '両方可')], default='offline', max_length=20, verbose_name='面談形式'),
        ),
        migrations.AddField(
            model_name='cat',
            name='spay_neuter_status',
            field=models.CharField(choices=[('not_yet', '未'), ('done', '済'), ('planned', '予定'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='不妊去勢'),
        ),
        migrations.AddField(
            model_name='cat',
            name='transfer_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='譲渡費用'),
        ),
        migrations.AddField(
            model_name='cat',
            name='trial_period',
            field=models.CharField(blank=True, help_text='例: 2週間, なし', max_length=100, verbose_name='トライアル期間'),
        ),
        migrations.AddField(
            model_name='cat',
            name='vaccination_status',
            field=models.CharField(choices=[('not_yet', '未'), ('partial', '一部'), ('done', '済'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='ワクチン'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age_months',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='年齢（月）'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age_years',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='年齢（年）'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True, verbose_name='紹介文（短文）'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('male', 'オス'), ('female', 'メス'), ('unknown', '不明')], default='unknown', max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前（仮名OK）'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='neutered',
            field=models.BooleanField(default=False, verbose_name='不妊去勢（旧）'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='personality',
            field=models.TextField(blank=True, verbose_name='性格詳細'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('open', '募集中'), ('paused', '一時停止'), ('in_review', '審査中'), ('trial', 'トライアル中'), ('adopted', '譲渡済み')], default='open', max_length=20, verbose_name='募集ステータス'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='vaccination',
            field=models.BooleanField(default=False, verbose_name='ワクチン（旧）'),
        ),
    ]
