# Generated by Django 4.2.28 on 2026-02-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_remove_cat_health_status_cat_activity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='age_years',
        ),
    ]
