# Generated by Django 4.2.28 on 2026-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_remove_cat_age_months_remove_cat_age_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_public',
            field=models.BooleanField(default=False, help_text='承認済みの団体のみ公開可能です', verbose_name='公開設定'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='estimated_age',
            field=models.CharField(blank=True, default='', help_text='例: 2歳くらい, 2023年春生まれ', max_length=100, verbose_name='推定年齢'),
        ),
    ]
