# Generated by Django 5.0.1 on 2026-02-05 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '応募直後'), ('reviewing', '確認/面談調整中'), ('accepted', '成立'), ('rejected', '不成立'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('message', models.TextField(blank=True, verbose_name='応募時メッセージ')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('occupation', models.CharField(max_length=100, verbose_name='職業')),
                ('phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
                ('address', models.TextField(verbose_name='住所')),
                ('housing_type', models.CharField(max_length=100, verbose_name='住居タイプ')),
                ('has_garden', models.BooleanField(default=False, verbose_name='庭の有無')),
                ('family_members', models.IntegerField(verbose_name='家族構成（人数）')),
                ('has_other_pets', models.BooleanField(default=False, verbose_name='他のペットの有無')),
                ('other_pets_description', models.TextField(blank=True, verbose_name='他のペットの詳細')),
                ('has_experience', models.BooleanField(default=False, verbose_name='飼育経験の有無')),
                ('experience_description', models.TextField(blank=True, verbose_name='飼育経験の詳細')),
                ('motivation', models.TextField(verbose_name='応募動機')),
                ('additional_notes', models.TextField(blank=True, verbose_name='その他・備考')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='応募日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='応募者')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cats.cat', verbose_name='保護猫')),
                ('shelter', models.ForeignKey(help_text='猫の所属団体（検索性向上のため冗長保持）', on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to=settings.AUTH_USER_MODEL, verbose_name='保護団体')),
            ],
            options={
                'verbose_name': '応募',
                'verbose_name_plural': '応募',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_changed', 'ステータス変更'), ('note', 'メモ'), ('system', 'システム')], max_length=20, verbose_name='イベント種別')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='変更前ステータス')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='変更後ステータス')),
                ('actor_type', models.CharField(choices=[('user', 'ユーザー'), ('shelter', '保護団体'), ('admin', '管理者'), ('system', 'システム')], max_length=20, verbose_name='実行者種別')),
                ('actor_id', models.IntegerField(verbose_name='実行者ID')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発生日時')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application', verbose_name='応募')),
            ],
            options={
                'verbose_name': '応募イベント',
                'verbose_name_plural': '応募イベント',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'ユーザー'), ('shelter', '保護団体'), ('admin', '管理者')], max_length=20, verbose_name='送信者種別')),
                ('content', models.TextField(verbose_name='メッセージ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.application', verbose_name='応募')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='application_applica_a7c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['cat'], name='application_cat_id_cef07c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['shelter'], name='application_shelter_1fb46e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('cat', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application'], name='application_applica_c21415_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['created_at'], name='application_created_b23ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['application'], name='application_applica_f00341_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='application_created_6d2c9a_idx'),
        ),
    ]
