# Generated by Django 5.0.1 on 2026-02-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationevent',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='システムイベントの場合はNULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to=settings.AUTH_USER_MODEL, verbose_name='実行者'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', '応募直後'), ('reviewing', '確認/面談調整中'), ('accepted', '成立'), ('rejected', '不成立'), ('cancelled', 'キャンセル')], max_length=20, null=True, verbose_name='変更前ステータス'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('pending', '応募直後'), ('reviewing', '確認/面談調整中'), ('accepted', '成立'), ('rejected', '不成立'), ('cancelled', 'キャンセル')], max_length=20, null=True, verbose_name='変更後ステータス'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['actor'], name='application_actor_i_a01fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='application_sender__051da3_idx'),
        ),
    ]
