# Generated by Django 5.0.1 on 2026-02-05 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_applicationevent_actor_id_and_more'),
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['cat', 'status'], name='application_cat_id_1cb4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['shelter', 'status'], name='application_shelter_a5feaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'reviewing', 'accepted'])), fields=('cat', 'applicant'), name='unique_active_application'),
        ),
    ]
