# Generated by Django 5.0.1 on 2026-02-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_unique_together_and_more'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='shelter',
            field=models.ForeignKey(help_text='猫の所属団体（検索性向上のため冗長保持）', on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to='shelters.shelter', verbose_name='保護団体'),
        ),
    ]
