# Generated by Django 5.0.1 on 2026-02-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='電話番号'),
        ),
    ]
