# Generated by Django 5.0.1 on 2026-02-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='application',
            name='family_members',
            field=models.PositiveSmallIntegerField(verbose_name='家族構成（人数）'),
        ),
    ]
