# Generated by Django 5.0.1 on 2026-02-06 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='application',
            name='family_members',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)], verbose_name='家族構成（人数）'),
        ),
    ]
