# Generated by Django 4.2.28 on 2026-02-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_age_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_active_application',
        ),
        migrations.RemoveField(
            model_name='application',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experience_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='family_members',
        ),
        migrations.RemoveField(
            model_name='application',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_experience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_garden',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_other_pets',
        ),
        migrations.RemoveField(
            model_name='application',
            name='housing_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='other_pets_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='application',
            name='allergy_status',
            field=models.BooleanField(default=False, help_text='家族含む', verbose_name='アレルギー有無'),
        ),
        migrations.AddField(
            model_name='application',
            name='cafe_data_sharing_consent',
            field=models.BooleanField(default=False, verbose_name='カフェへの情報提供同意'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_available',
            field=models.BooleanField(default=False, verbose_name='緊急時の預け先の有無'),
        ),
        migrations.AddField(
            model_name='application',
            name='family_consent',
            field=models.BooleanField(default=False, verbose_name='家族全員の同意'),
        ),
        migrations.AddField(
            model_name='application',
            name='income_status',
            field=models.CharField(choices=[('stable', '安定'), ('unstable', 'やや不安定')], default='stable', max_length=20, verbose_name='収入状況'),
        ),
        migrations.AddField(
            model_name='application',
            name='lifelong_care_agreement',
            field=models.BooleanField(default=False, verbose_name='終生飼養への同意'),
        ),
        migrations.AddField(
            model_name='application',
            name='medical_cost_understanding',
            field=models.BooleanField(default=False, verbose_name='医療費負担への理解'),
        ),
        migrations.AddField(
            model_name='application',
            name='spay_neuter_agreement',
            field=models.BooleanField(default=False, verbose_name='不妊去勢への同意'),
        ),
        migrations.AddField(
            model_name='application',
            name='term_agreement',
            field=models.BooleanField(default=False, verbose_name='利用規約・個人情報保護方針への同意'),
        ),
    ]
