# Generated by Django 4.2.28 on 2026-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_application_unique_active_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_hidden_by_applicant',
            field=models.BooleanField(default=False, verbose_name='応募者側で非表示'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_hidden_by_shelter',
            field=models.BooleanField(default=False, verbose_name='団体側で非表示'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '新着（未確認）'), ('reviewing', '審査・面談中'), ('trial', 'トライアル中'), ('accepted', '譲渡完了'), ('rejected', 'お断り'), ('cancelled', 'キャンセル済み')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', '新着（未確認）'), ('reviewing', '審査・面談中'), ('trial', 'トライアル中'), ('accepted', '譲渡完了'), ('rejected', 'お断り'), ('cancelled', 'キャンセル済み')], max_length=20, null=True, verbose_name='変更前ステータス'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('pending', '新着（未確認）'), ('reviewing', '審査・面談中'), ('trial', 'トライアル中'), ('accepted', '譲渡完了'), ('rejected', 'お断り'), ('cancelled', 'キャンセル済み')], max_length=20, null=True, verbose_name='変更後ステータス'),
        ),
    ]
